name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发
  workflow_dispatch:    # 允许手动触发

# Add permissions to allow the workflow to push to GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Specify pnpm version

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies 📦
        run: pnpm install

      - name: Build 🔧
        run: pnpm run build

      - name: Add .nojekyll file 📄
        run: touch out/.nojekyll

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # 部署到 gh-pages 分支
          folder: out       # 要部署的文件夹
          clean: true       # 自动删除旧文件